config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' =>'home#index'
  get '/about'=> 'home#about', as: :about
  get '/admin/question' => 'admin/question#index', as: :question
  # delete '/admin/question/:id' => 'admin/question#destroy', as: :destroy
  # patch 'admin/question/:id' => 'admin/question#edit', as: :edit
  # put 'admin/question/:id' => 'admin/question#show', as: :show
  get '/namepicker' => 'namepicker#index'
  post '/namepicker' => 'namepicker#index'
  get '/billsplitter' => 'billsplitter#index'
  post '/billsplitter' => 'billsplitter#index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/question_controller.rb
class Admin::QuestionController < ApplicationController
  def question

    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/billsplitter_controller.rb
class BillsplitterController < ApplicationController
  def index
    @amount = params[:amount].to_f
        @tax = params[:tax].to_f
        @tip = params[:tip].to_f
        @nop = params[:nop].to_f
        @tax_output = @amount * (@tax / 100)
        @tip_output = @amount * (@tip / 100)
        p @total = (@tax + @tip + @amount) / @nop
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  def about
  end
end

app/controllers/namepicker_controller.rb
class NamepickerController < ApplicationController
  def index

    @names = params[:names]
    @array = @names.to_s.split(',')
    if @names.nil?
      @dd = ""
    else
      @dd = @array[rand(0..@array.length-1)]
    end

  end

end

app/helpers/admin/question_helper.rb
module Admin::QuestionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billsplitter_helper.rb
module BillsplitterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/namepicker_helper.rb
module NamepickerHelper
end

app/views/admin/question/index.html.erb
Hello wordlds

app/views/billsplitter/index.html.erb
<h1> Bill splitter </h1>

<div class="col-md-6">
 <%= form_tag billsplitter_path do %>
   <div class="form-group">
     <label for="amount">Amount</label>
     <div class="input-group">
        <div class="input-group-addon">$</div>
        <input type="text" id="amount" name="amount" class="form-control" value="">
     </div>
   </div>

   <div class="form-group">
     <label for="tax">Tax</label>
     <div class="input-group">
        <div class="input-group-addon">%</div>
        <input type="text" id="tax" name="tax" class="form-control" value="">
     </div>
   </div>

   <div class="form-group">
     <label for="tip">Tip</label>
     <div class="input-group">
        <div class="input-group-addon">%</div>
        <input type="text" id="tip" name="tip" class="form-control" value="">
     </div>
   </div>

   <div class="form-group">
     <label for="count">Number Of People</label>
     <input type="text" id="count" name="nop" class="form-control" value="">
   </div>

   <input type="submit" value="Submit" class="btn btn-primary">
<% end %>
</div>
<div class="row">
  <div class="col-md-12">
<% if @total.nan? %>
<% else %>
      <h1><span class="label label-primary"><%= "Each person should pay #{(@total).round(2)}" %></span></h1>
<% end %>
  </div>
</div>

app/views/home/about.html.erb
<h1>This is about me </h1>
<p>also you can my photo here</p>
<%= image_tag("http://media.gettyimages.com/videos/little-girl-swimming-underwater-in-swimming-pool-video-id491004802?s=640x640",  alt: "like", class: 'img-responsive' ) %>

app/views/home/index.html.erb
<h1>Welcome to my blog</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-inverse navbar-static-top">
         <div class="container">
           <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="/">My Blog</a>
           </div>
           <div id="navbar" class="navbar-collapse collapse">
             <ul class="nav navbar-nav navbar-right">
               <li class="active"><%= link_to "Home", root_path %>
               |</li>
               <li> <%= link_to "about", about_path %></li>
               <li><%= link_to "question", question_path %></li>
               <li><%= link_to "namepicker", namepicker_path %></li>
               <li><%= link_to "billsplitter", billsplitter_path %></li>

             </ul>
           </div>
         </div>
       </nav>

    <%= yield %>
  </body>
</html>

app/views/namepicker/index.html.erb
<h1> Random name picker </h1>
<%= form_tag namepicker_path do %>
<!-- <%= text_area_tag 'names', class: 'form-control' %> -->
<textarea name='names' class="form-control" rows="3" cols="4" width= 50% > names seperated by commas</textarea>
<div>
<%= submit_tag "pick winner" %>
</div>
<% end %>
<% if @names.is_a? String %>
<%="The winner is #{@dd}" %>
<% end %>